import type { Event } from "./types";

export const MOCK_EVENTS: Event[] = [
  // ─── NSW ───────────────────────────────────────────────────────────────────
  {
    id: "evt-001",
    title: "Sydney Mardi Gras Festival",
    description: "The world-famous parade and festival celebrating LGBTQ+ culture with spectacular performances across the city.",
    date: "2025-03-01", endDate: "2025-03-02", time: "19:30",
    location: { venue: "Oxford Street", city: "Sydney", state: "NSW", lat: -33.8773, lng: 151.2213 },
    category: "cultural", tags: ["LGBTQ+", "parade", "festival"], price: null, featured: true,
    website: "https://www.mardigras.org.au",
  },
  {
    id: "evt-002",
    title: "Vivid Sydney",
    description: "Sydney's iconic festival of light, music and ideas transforming the city into a canvas of colour.",
    date: "2025-05-23", endDate: "2025-06-14", time: "18:00",
    location: { venue: "Sydney Opera House", city: "Sydney", state: "NSW", lat: -33.8568, lng: 151.2153 },
    category: "arts", tags: ["lights", "projections", "free", "family"], price: null, featured: true,
    website: "https://www.vividsydney.com",
  },
  {
    id: "evt-003",
    title: "Splendour in the Grass",
    description: "Australia's largest music festival featuring hundreds of acts across multiple stages in Byron Bay.",
    date: "2025-07-18", endDate: "2025-07-20", time: "12:00",
    location: { venue: "North Byron Parklands", city: "Byron Bay", state: "NSW", lat: -28.5957, lng: 153.4285 },
    category: "music", tags: ["festival", "camping", "indie", "electronic"], price: 399, featured: true,
    website: "https://www.splendourinthegrass.com",
  },
  {
    id: "evt-004",
    title: "Bluesfest Byron Bay",
    description: "Five days of blues, roots, and world music with 200+ performances from local and international artists.",
    date: "2025-04-17", endDate: "2025-04-21", time: "11:00",
    location: { venue: "Tyagarah Tea Tree Farm", city: "Byron Bay", state: "NSW", lat: -28.6418, lng: 153.5639 },
    category: "music", tags: ["blues", "roots", "world music", "camping"], price: 315, featured: false,
    website: "https://www.bluesfest.com.au",
  },
  {
    id: "evt-005",
    title: "Sydney Running Festival",
    description: "The world's most scenic run through Sydney Harbour Bridge, Opera House, and the CBD.",
    date: "2025-09-14", time: "07:00",
    location: { venue: "Sydney CBD", city: "Sydney", state: "NSW", lat: -33.8688, lng: 151.2093 },
    category: "sports", tags: ["running", "marathon", "harbour", "fitness"], price: 85, featured: false,
    website: "https://www.sydneyrunningfestival.com.au",
  },
  {
    id: "evt-006",
    title: "Tropfest Short Film Festival",
    description: "The world's largest short film festival, screened outdoors simultaneously in cities across Australia.",
    date: "2025-11-22", time: "18:00",
    location: { venue: "Centennial Parklands", city: "Sydney", state: "NSW", lat: -33.8886, lng: 151.2311 },
    category: "film", tags: ["short film", "outdoor cinema", "free", "competition"], price: null, featured: false,
    website: "https://www.tropfest.com",
  },
  {
    id: "evt-007",
    title: "Newcastle Jazz Festival",
    description: "A celebration of jazz across multiple venues in Newcastle's CBD and harbourside precinct.",
    date: "2025-05-02", endDate: "2025-05-04", time: "12:00",
    location: { venue: "Newcastle City Hall", city: "Newcastle", state: "NSW", lat: -32.9267, lng: 151.7789 },
    category: "music", tags: ["jazz", "live music", "family"], price: 40, featured: false,
    website: "https://www.newcastlejazzfestival.com.au",
  },
  {
    id: "evt-008",
    title: "Sydney Film Festival",
    description: "One of the world's longest-running film festivals, showcasing the best in Australian and international cinema.",
    date: "2025-06-04", endDate: "2025-06-15", time: "10:00",
    location: { venue: "State Theatre Sydney", city: "Sydney", state: "NSW", lat: -33.8712, lng: 151.2073 },
    category: "film", tags: ["cinema", "international", "premiere", "awards"], price: 28, featured: false,
    website: "https://www.sff.org.au",
  },
  {
    id: "evt-009",
    title: "Tamworth Country Music Festival",
    description: "Australia's biggest country music celebration — ten days of gigs, awards, and bush spirit.",
    date: "2025-01-17", endDate: "2025-01-26", time: "09:00",
    location: { venue: "Tamworth CBD", city: "Tamworth", state: "NSW", lat: -31.0930, lng: 150.9320 },
    category: "music", tags: ["country", "awards", "bush", "family"], price: null, featured: true,
    website: "https://www.tcmf.com.au",
  },
  {
    id: "evt-010",
    title: "Sydney Royal Easter Show",
    description: "The iconic agricultural show with carnival rides, animal exhibits, showbags, and entertainment.",
    date: "2025-04-11", endDate: "2025-04-23", time: "09:00",
    location: { venue: "Sydney Showground", city: "Sydney", state: "NSW", lat: -33.8457, lng: 151.0673 },
    category: "cultural", tags: ["family", "agriculture", "carnival", "animals"], price: 42, featured: false,
    website: "https://www.eastershow.com.au",
  },
  {
    id: "evt-011",
    title: "Sculpture by the Sea",
    description: "The world's largest free outdoor sculpture exhibition, spanning Bondi to Tamarama coastal walk.",
    date: "2025-10-23", endDate: "2025-11-09", time: "07:00",
    location: { venue: "Bondi Beach", city: "Sydney", state: "NSW", lat: -33.8915, lng: 151.2767 },
    category: "arts", tags: ["sculpture", "outdoor", "coastal", "free"], price: null, featured: true,
    website: "https://www.sculpturebythesea.com",
  },
  {
    id: "evt-012",
    title: "Wollongong Viva La Gong Festival",
    description: "Street performers, live music, and arts events transforming the streets of Wollongong.",
    date: "2025-10-18", time: "10:00",
    location: { venue: "Crown Street Mall", city: "Wollongong", state: "NSW", lat: -34.4278, lng: 150.8931 },
    category: "arts", tags: ["street art", "performance", "free", "family"], price: null, featured: false,
    website: "https://www.vivalagong.com.au",
  },
  {
    id: "evt-013",
    title: "Hunter Valley Harvest Festival",
    description: "Celebrating the Hunter Valley wine harvest with tastings, food pairings, and live entertainment.",
    date: "2025-03-29", endDate: "2025-04-06", time: "10:00",
    location: { venue: "Various Wineries", city: "Hunter Valley", state: "NSW", lat: -32.7850, lng: 151.2865 },
    category: "food", tags: ["wine", "harvest", "food pairing", "regional"], price: 55, featured: false,
    website: "https://www.huntervalley.com.au/event/harvest-festival",
  },
  {
    id: "evt-014",
    title: "Maitland Steamfest",
    description: "Australia's largest steam festival showcasing heritage steam locomotives and machinery.",
    date: "2025-04-12", endDate: "2025-04-13", time: "09:00",
    location: { venue: "Maitland Showground", city: "Maitland", state: "NSW", lat: -32.7339, lng: 151.5540 },
    category: "cultural", tags: ["heritage", "trains", "steam", "family"], price: 22, featured: false,
    website: "https://www.steamfest.com.au",
  },
  {
    id: "evt-015",
    title: "Bangalow Music Festival",
    description: "A boutique music festival in the charming Northern Rivers village of Bangalow.",
    date: "2025-04-25", endDate: "2025-04-27", time: "14:00",
    location: { venue: "Bangalow Showground", city: "Bangalow", state: "NSW", lat: -28.6882, lng: 153.5202 },
    category: "music", tags: ["boutique", "acoustic", "village", "community"], price: 80, featured: false,
    website: "https://www.bangalowmusicfestival.com",
  },

  // ─── VIC ───────────────────────────────────────────────────────────────────
  {
    id: "evt-016",
    title: "Laneway Festival Melbourne",
    description: "Australia's premier boutique music festival showcasing local and international indie artists in inner-city laneways.",
    date: "2025-03-08", time: "12:00",
    location: { venue: "Footscray Community Arts", city: "Melbourne", state: "VIC", lat: -37.8006, lng: 144.8979 },
    category: "music", tags: ["indie", "alternative", "live music"], price: 149, featured: true,
    website: "https://www.lanewayfestival.com",
  },
  {
    id: "evt-017",
    title: "Melbourne Comedy Festival",
    description: "The largest comedy festival in the Southern Hemisphere with over 10,000 shows from 600+ performers.",
    date: "2025-03-26", endDate: "2025-04-20", time: "19:00",
    location: { venue: "Melbourne Town Hall", city: "Melbourne", state: "VIC", lat: -37.8136, lng: 144.9631 },
    category: "comedy", tags: ["comedy", "stand-up", "improv", "cabaret"], price: 30, featured: true,
    website: "https://www.comedyfestival.com.au",
  },
  {
    id: "evt-018",
    title: "Melbourne Food & Wine Festival",
    description: "Australia's most prestigious culinary event celebrating the finest food and wine from around the country.",
    date: "2025-03-14", endDate: "2025-03-23", time: "10:00",
    location: { venue: "Federation Square", city: "Melbourne", state: "VIC", lat: -37.8180, lng: 144.9691 },
    category: "food", tags: ["fine dining", "masterclass", "wine", "chefs"], price: 65, featured: true,
    website: "https://www.melbournefoodandwine.com.au",
  },
  {
    id: "evt-019",
    title: "Melbourne International Film Festival",
    description: "One of the oldest and most prestigious film festivals in the Asia-Pacific region.",
    date: "2025-07-31", endDate: "2025-08-17", time: "10:00",
    location: { venue: "ACMI Federation Square", city: "Melbourne", state: "VIC", lat: -37.8184, lng: 144.9691 },
    category: "film", tags: ["international cinema", "premiere", "documentary", "arts"], price: 22, featured: false,
    website: "https://www.miff.com.au",
  },
  {
    id: "evt-020",
    title: "Melbourne Fringe Festival",
    description: "Melbourne's most adventurous arts festival celebrating independent and experimental work.",
    date: "2025-09-17", endDate: "2025-10-05", time: "10:00",
    location: { venue: "Arts House", city: "Melbourne", state: "VIC", lat: -37.8067, lng: 144.9558 },
    category: "arts", tags: ["independent", "experimental", "theatre", "dance"], price: 25, featured: false,
    website: "https://www.melbournefringe.com.au",
  },
  {
    id: "evt-021",
    title: "Melbourne Cup Carnival",
    description: "The race that stops a nation — the Melbourne Cup and four days of premium racing at Flemington.",
    date: "2025-10-30", endDate: "2025-11-08", time: "10:00",
    location: { venue: "Flemington Racecourse", city: "Melbourne", state: "VIC", lat: -37.7940, lng: 144.9065 },
    category: "sports", tags: ["horse racing", "fashion", "carnival", "iconic"], price: 90, featured: true,
    website: "https://www.flemington.com.au/melbourne-cup-carnival",
  },
  {
    id: "evt-022",
    title: "Australian Open Tennis",
    description: "The first Grand Slam of the year, held at Melbourne Park in the Australian summer heat.",
    date: "2025-01-13", endDate: "2025-01-26", time: "10:00",
    location: { venue: "Melbourne Park", city: "Melbourne", state: "VIC", lat: -37.8252, lng: 144.9789 },
    category: "sports", tags: ["tennis", "Grand Slam", "summer", "international"], price: 60, featured: true,
    website: "https://www.ausopen.com",
  },
  {
    id: "evt-023",
    title: "White Night Melbourne",
    description: "A night-time arts and culture festival transforming Melbourne's city centre with light installations.",
    date: "2025-08-16", time: "19:00",
    location: { venue: "Melbourne CBD", city: "Melbourne", state: "VIC", lat: -37.8136, lng: 144.9631 },
    category: "arts", tags: ["lights", "night festival", "free", "outdoor"], price: null, featured: false,
    website: "https://www.whitenight.com.au",
  },
  {
    id: "evt-024",
    title: "Geelong After Dark Festival",
    description: "Geelong's vibrant night festival of art, music, and food activating the city after hours.",
    date: "2025-06-21", time: "17:00",
    location: { venue: "Little Malop Street", city: "Geelong", state: "VIC", lat: -38.1499, lng: 144.3617 },
    category: "arts", tags: ["night festival", "street art", "food", "music"], price: null, featured: false,
    website: "https://www.geelongafterdark.com.au",
  },
  {
    id: "evt-025",
    title: "Meredith Music Festival",
    description: "The legendary boutique camping music festival known for its no dickheads policy and incredible lineup.",
    date: "2025-12-12", endDate: "2025-12-14", time: "12:00",
    location: { venue: "Meredith Supernatural Amphitheatre", city: "Meredith", state: "VIC", lat: -37.8419, lng: 144.0602 },
    category: "music", tags: ["boutique", "camping", "electronic", "indie"], price: 320, featured: false,
    website: "https://www.meredithmusicfestival.com",
  },
  {
    id: "evt-026",
    title: "Melbourne Jazz Festival",
    description: "Celebrating jazz in all its forms across Melbourne's iconic venues and outdoor spaces.",
    date: "2025-05-30", endDate: "2025-06-08", time: "12:00",
    location: { venue: "Hamer Hall", city: "Melbourne", state: "VIC", lat: -37.8222, lng: 144.9693 },
    category: "music", tags: ["jazz", "blues", "soul", "live music"], price: 45, featured: false,
    website: "https://www.melbournejazz.com",
  },
  {
    id: "evt-027",
    title: "St Kilda Festival",
    description: "One of Australia's largest free music festivals with over 100,000 visitors on the St Kilda foreshore.",
    date: "2025-02-09", time: "12:00",
    location: { venue: "St Kilda Foreshore", city: "Melbourne", state: "VIC", lat: -37.8600, lng: 144.9758 },
    category: "music", tags: ["free", "beach", "family", "community"], price: null, featured: false,
    website: "https://www.stkildafestival.com.au",
  },
  {
    id: "evt-028",
    title: "Melbourne International Flower & Garden Show",
    description: "The Southern Hemisphere's largest flower and garden show at the Royal Exhibition Building.",
    date: "2025-03-26", endDate: "2025-03-30", time: "09:00",
    location: { venue: "Carlton Gardens", city: "Melbourne", state: "VIC", lat: -37.8047, lng: 144.9717 },
    category: "cultural", tags: ["garden", "flowers", "design", "family"], price: 35, featured: false,
    website: "https://www.melbflowershow.com.au",
  },

  // ─── QLD ───────────────────────────────────────────────────────────────────
  {
    id: "evt-029",
    title: "Brisbane Festival",
    description: "Queensland's premier arts festival featuring world-class theatre, dance, music, and the spectacular Riverfire.",
    date: "2025-09-05", endDate: "2025-09-27", time: "09:00",
    location: { venue: "South Bank Parklands", city: "Brisbane", state: "QLD", lat: -27.4764, lng: 153.0218 },
    category: "arts", tags: ["theatre", "dance", "Riverfire", "fireworks"], price: 35, featured: true,
    website: "https://www.brisbanefestival.com.au",
  },
  {
    id: "evt-030",
    title: "Brisbane Food & Wine Festival",
    description: "Three days of incredible food, wine, and culinary experiences from Queensland's best chefs.",
    date: "2025-05-16", endDate: "2025-05-18", time: "11:00",
    location: { venue: "Howard Smith Wharves", city: "Brisbane", state: "QLD", lat: -27.4611, lng: 153.0428 },
    category: "food", tags: ["food", "wine", "chefs", "Queensland"], price: 35, featured: false,
    website: "https://www.brisbanefoodandwinefestival.com.au",
  },
  {
    id: "evt-031",
    title: "Surfers Paradise Film Festival",
    description: "A week of indie films, director Q&As, and beach screenings on the Gold Coast.",
    date: "2025-04-10", endDate: "2025-04-16", time: "11:00",
    location: { venue: "HOYTS Surfers Paradise", city: "Gold Coast", state: "QLD", lat: -28.0023, lng: 153.4145 },
    category: "film", tags: ["indie film", "cinema", "directors"], price: 18, featured: false,
    website: "https://www.spiff.com.au",
  },
  {
    id: "evt-032",
    title: "Gold Coast 600",
    description: "Supercars Championship street race through the heart of Surfers Paradise.",
    date: "2025-10-24", endDate: "2025-10-26", time: "10:00",
    location: { venue: "Surfers Paradise Street Circuit", city: "Gold Coast", state: "QLD", lat: -27.9938, lng: 153.4301 },
    category: "sports", tags: ["motorsport", "Supercars", "street circuit"], price: 120, featured: false,
    website: "https://www.supercars.com/events/gold-coast",
  },
  {
    id: "evt-033",
    title: "Cairns Indigenous Art Fair",
    description: "Australia's largest indigenous art marketplace celebrating the creative spirit of First Nations artists.",
    date: "2025-07-18", endDate: "2025-07-20", time: "10:00",
    location: { venue: "Cairns Convention Centre", city: "Cairns", state: "QLD", lat: -16.9203, lng: 145.7710 },
    category: "arts", tags: ["indigenous", "art", "culture", "First Nations"], price: 20, featured: false,
    website: "https://www.ciaf.com.au",
  },
  {
    id: "evt-034",
    title: "Woodford Folk Festival",
    description: "One of Australia's great cultural gatherings — six days of music, dance, arts, and ideas.",
    date: "2025-12-27", endDate: "2026-01-01", time: "09:00",
    location: { venue: "Woodford Showgrounds", city: "Woodford", state: "QLD", lat: -26.9680, lng: 152.7782 },
    category: "music", tags: ["folk", "camping", "family", "cultural"], price: 280, featured: true,
    website: "https://www.woodfordfolkfestival.com",
  },
  {
    id: "evt-035",
    title: "Noosa Food & Wine Festival",
    description: "Celebrating the best of Australian produce and hospitality in beautiful Noosa.",
    date: "2025-05-15", endDate: "2025-05-18", time: "10:00",
    location: { venue: "Noosa Heads Foreshore", city: "Noosa", state: "QLD", lat: -26.3927, lng: 153.0935 },
    category: "food", tags: ["food", "wine", "beachside", "celebrity chefs"], price: 85, featured: false,
    website: "https://www.noosafoodandwine.com.au",
  },
  {
    id: "evt-036",
    title: "Townsville Cultural Festival",
    description: "North Queensland's vibrant celebration of multicultural heritage with food, music, and performance.",
    date: "2025-08-02", endDate: "2025-08-03", time: "10:00",
    location: { venue: "Strand Park", city: "Townsville", state: "QLD", lat: -19.2576, lng: 146.8239 },
    category: "cultural", tags: ["multicultural", "family", "food", "North Queensland"], price: null, featured: false,
    website: "https://www.townsvilleenterprise.com.au/events",
  },
  {
    id: "evt-037",
    title: "Brisbane Comedy Festival",
    description: "Brisbane's dedicated comedy festival bringing the best local and international comedians to town.",
    date: "2025-03-14", endDate: "2025-03-30", time: "19:00",
    location: { venue: "Brisbane Powerhouse", city: "Brisbane", state: "QLD", lat: -27.4620, lng: 153.0418 },
    category: "comedy", tags: ["comedy", "stand-up", "improv"], price: 35, featured: false,
    website: "https://www.brisbanecomedyfestival.com.au",
  },
  {
    id: "evt-038",
    title: "Sunsuper Riverfire",
    description: "Brisbane's spectacular fireworks display over the river, closing the Brisbane Festival in style.",
    date: "2025-09-27", time: "19:30",
    location: { venue: "Brisbane Riverwalk", city: "Brisbane", state: "QLD", lat: -27.4705, lng: 153.0351 },
    category: "cultural", tags: ["fireworks", "free", "river", "spectacle"], price: null, featured: true,
    website: "https://www.brisbanefestival.com.au/riverfire",
  },

  // ─── WA ────────────────────────────────────────────────────────────────────
  {
    id: "evt-039",
    title: "Perth International Arts Festival",
    description: "Western Australia's iconic arts festival featuring theatre, dance, music, and visual arts.",
    date: "2025-02-14", endDate: "2025-03-09", time: "10:00",
    location: { venue: "Perth Cultural Centre", city: "Perth", state: "WA", lat: -31.9505, lng: 115.8605 },
    category: "arts", tags: ["theatre", "dance", "visual arts"], price: 45, featured: true,
    website: "https://www.perthfestival.com.au",
  },
  {
    id: "evt-040",
    title: "Fremantle Night Markets",
    description: "Perth's best night market with street food, live music, and artisan vendors every Friday night.",
    date: "2025-03-07", time: "16:00",
    location: { venue: "Fremantle Fishing Boat Harbour", city: "Fremantle", state: "WA", lat: -32.0569, lng: 115.7439 },
    category: "markets", tags: ["street food", "night market", "live music", "weekly"], price: null, featured: false,
    website: "https://www.fremantlemarkets.com.au",
  },
  {
    id: "evt-041",
    title: "Margaret River Gourmet Escape",
    description: "World-class chefs, winemakers, and food lovers descend on Margaret River for this epic food festival.",
    date: "2025-11-14", endDate: "2025-11-16", time: "10:00",
    location: { venue: "McLeod Estate", city: "Margaret River", state: "WA", lat: -33.9527, lng: 115.0748 },
    category: "food", tags: ["gourmet", "wine", "celebrity chefs", "Margaret River"], price: 150, featured: true,
    website: "https://www.gourmetescape.com.au",
  },
  {
    id: "evt-042",
    title: "Sculpture by the Sea Cottesloe",
    description: "Stunning sculptures dot Cottesloe Beach as part of this beloved outdoor art exhibition.",
    date: "2025-03-07", endDate: "2025-03-24", time: "07:00",
    location: { venue: "Cottesloe Beach", city: "Perth", state: "WA", lat: -31.9975, lng: 115.7493 },
    category: "arts", tags: ["sculpture", "beach", "outdoor", "free"], price: null, featured: false,
    website: "https://www.sculpturebythesea.com/cottesloe",
  },
  {
    id: "evt-043",
    title: "Rottnest Channel Swim",
    description: "One of the world's largest open-water swimming events — 19.7km from Cottesloe to Rottnest Island.",
    date: "2025-02-22", time: "06:30",
    location: { venue: "Cottesloe Beach", city: "Perth", state: "WA", lat: -31.9975, lng: 115.7493 },
    category: "sports", tags: ["swimming", "open water", "ocean", "endurance"], price: 95, featured: false,
    website: "https://www.rottnestchannelswim.com.au",
  },
  {
    id: "evt-044",
    title: "Ord Valley Muster",
    description: "An extraordinary outback festival in the Kimberley with concerts under the stars at Lake Argyle.",
    date: "2025-05-15", endDate: "2025-05-25", time: "17:00",
    location: { venue: "Lake Argyle", city: "Kununurra", state: "WA", lat: -16.1106, lng: 128.7453 },
    category: "music", tags: ["outback", "Kimberley", "outdoor", "stars"], price: 180, featured: true,
    website: "https://www.ordvalleymuster.com.au",
  },
  {
    id: "evt-045",
    title: "Perth Comedy Festival",
    description: "Western Australia's biggest comedy festival with local and international acts across the city.",
    date: "2025-04-23", endDate: "2025-05-11", time: "19:00",
    location: { venue: "Riverside Theatre", city: "Perth", state: "WA", lat: -31.9523, lng: 115.8613 },
    category: "comedy", tags: ["comedy", "stand-up", "festival"], price: 35, featured: false,
    website: "https://www.perthcomedyfestival.com.au",
  },
  {
    id: "evt-046",
    title: "Broome Mango Festival",
    description: "Celebrating the famous Kununurra and Broome mango season with food, music, and tropical fun.",
    date: "2025-11-01", endDate: "2025-11-02", time: "09:00",
    location: { venue: "Town Beach", city: "Broome", state: "WA", lat: -17.9614, lng: 122.2359 },
    category: "food", tags: ["mango", "tropical", "community", "family"], price: null, featured: false,
    website: "https://www.broomemangofestival.com.au",
  },

  // ─── SA ────────────────────────────────────────────────────────────────────
  {
    id: "evt-047",
    title: "Adelaide Fringe Festival",
    description: "The world's second largest arts festival — over 1,200 shows in 300+ venues across Adelaide.",
    date: "2025-02-21", endDate: "2025-03-23", time: "09:00",
    location: { venue: "Various Venues", city: "Adelaide", state: "SA", lat: -34.9285, lng: 138.6007 },
    category: "arts", tags: ["fringe", "comedy", "cabaret", "theatre"], price: 20, featured: true,
    website: "https://www.adelaidefringe.com.au",
  },
  {
    id: "evt-048",
    title: "WOMADelaide",
    description: "A four-day celebration of world music, arts, and dance in Adelaide's gorgeous Botanic Park.",
    date: "2025-03-07", endDate: "2025-03-10", time: "12:00",
    location: { venue: "Botanic Park", city: "Adelaide", state: "SA", lat: -34.9156, lng: 138.6120 },
    category: "music", tags: ["world music", "dance", "family", "multicultural"], price: 195, featured: true,
    website: "https://www.womadelaide.com.au",
  },
  {
    id: "evt-049",
    title: "Adelaide Festival of Arts",
    description: "Australia's premier international arts festival with extraordinary opera, theatre, and dance.",
    date: "2025-02-28", endDate: "2025-03-16", time: "09:00",
    location: { venue: "Adelaide Festival Centre", city: "Adelaide", state: "SA", lat: -34.9200, lng: 138.6034 },
    category: "arts", tags: ["opera", "theatre", "dance", "international"], price: 60, featured: true,
    website: "https://www.adelaidefestival.com.au",
  },
  {
    id: "evt-050",
    title: "Adelaide Cabaret Festival",
    description: "The only dedicated cabaret festival in Australia — 17 days of glitz, glamour, and song.",
    date: "2025-06-06", endDate: "2025-06-22", time: "19:00",
    location: { venue: "Adelaide Festival Centre", city: "Adelaide", state: "SA", lat: -34.9200, lng: 138.6034 },
    category: "arts", tags: ["cabaret", "burlesque", "song", "glamour"], price: 55, featured: false,
    website: "https://www.adelaidecabaretfestival.com.au",
  },
  {
    id: "evt-051",
    title: "Barossa Vintage Festival",
    description: "Celebrating the Barossa Valley wine harvest with tastings, tours, food, and live entertainment.",
    date: "2025-04-25", endDate: "2025-05-01", time: "10:00",
    location: { venue: "Seppeltsfield Winery", city: "Barossa Valley", state: "SA", lat: -34.5060, lng: 138.9030 },
    category: "food", tags: ["wine", "vintage", "Barossa", "harvest"], price: 40, featured: false,
    website: "https://www.barossavintagefestival.com.au",
  },
  {
    id: "evt-052",
    title: "Tour Down Under",
    description: "The first WorldTour cycling race of the year, tearing through the hills and streets of South Australia.",
    date: "2025-01-14", endDate: "2025-01-19", time: "10:00",
    location: { venue: "Various Stages", city: "Adelaide", state: "SA", lat: -34.9285, lng: 138.6007 },
    category: "sports", tags: ["cycling", "WorldTour", "professional", "hills"], price: null, featured: true,
    website: "https://www.tourdownunder.com.au",
  },
  {
    id: "evt-053",
    title: "Illuminate Adelaide",
    description: "Adelaide's winter light and ideas festival transforming dark winter nights into spectacular experiences.",
    date: "2025-07-18", endDate: "2025-08-03", time: "17:30",
    location: { venue: "Adelaide CBD", city: "Adelaide", state: "SA", lat: -34.9285, lng: 138.6007 },
    category: "arts", tags: ["lights", "winter", "immersive", "free"], price: null, featured: false,
    website: "https://www.illuminateadelaide.com",
  },
  {
    id: "evt-054",
    title: "Adelaide 500 Supercars",
    description: "Supercars roar through the streets of Adelaide's CBD in this thrilling street circuit race.",
    date: "2025-02-20", endDate: "2025-02-23", time: "10:00",
    location: { venue: "Adelaide Street Circuit", city: "Adelaide", state: "SA", lat: -34.9200, lng: 138.6034 },
    category: "sports", tags: ["motorsport", "street circuit", "Supercars", "speed"], price: 100, featured: false,
    website: "https://www.supercars.com/events/adelaide",
  },

  // ─── TAS ───────────────────────────────────────────────────────────────────
  {
    id: "evt-055",
    title: "Salamanca Market",
    description: "Tasmania's iconic open-air market with local arts, crafts, food, and live music every Saturday.",
    date: "2025-03-15", time: "08:30",
    location: { venue: "Salamanca Place", city: "Hobart", state: "TAS", lat: -42.8821, lng: 147.3272 },
    category: "markets", tags: ["market", "crafts", "local", "weekly"], price: null, featured: false,
    website: "https://www.salamancamarket.com.au",
  },
  {
    id: "evt-056",
    title: "Taste of Tasmania",
    description: "Hobart's premier food and drink festival celebrating Tasmania's world-class produce over the New Year.",
    date: "2025-12-27", endDate: "2026-01-02", time: "11:00",
    location: { venue: "Princes Wharf", city: "Hobart", state: "TAS", lat: -42.8839, lng: 147.3334 },
    category: "food", tags: ["Tasmania", "seafood", "cheese", "wine"], price: null, featured: true,
    website: "https://www.taste.net.au",
  },
  {
    id: "evt-057",
    title: "Dark Mofo",
    description: "MONA's winter festival of art, music, and ideas — provocative, immersive, and utterly unique.",
    date: "2025-06-13", endDate: "2025-06-22", time: "16:00",
    location: { venue: "MONA", city: "Hobart", state: "TAS", lat: -42.8276, lng: 147.2840 },
    category: "arts", tags: ["MONA", "dark", "immersive", "provocative"], price: 80, featured: true,
    website: "https://www.darkmofo.net.au",
  },
  {
    id: "evt-058",
    title: "Festival of Voices",
    description: "Australia's only winter choral festival, transforming Hobart with song across stunning venues.",
    date: "2025-07-04", endDate: "2025-07-13", time: "17:00",
    location: { venue: "Town Hall Hobart", city: "Hobart", state: "TAS", lat: -42.8826, lng: 147.3296 },
    category: "music", tags: ["choral", "singing", "choir", "winter"], price: 35, featured: false,
    website: "https://www.festivalofvoices.com",
  },
  {
    id: "evt-059",
    title: "Launceston Festivale",
    description: "Tasmania's largest food and drink festival held in the beautiful surrounds of City Park.",
    date: "2025-02-14", endDate: "2025-02-16", time: "11:00",
    location: { venue: "City Park", city: "Launceston", state: "TAS", lat: -41.4332, lng: 147.1441 },
    category: "food", tags: ["Tasmanian produce", "wine", "family", "outdoor"], price: null, featured: false,
    website: "https://www.festivale.com.au",
  },
  {
    id: "evt-060",
    title: "Unconformity Festival",
    description: "An arts festival in remote Queenstown, Tasmania — in an extraordinary industrial landscape.",
    date: "2025-10-24", endDate: "2025-10-26", time: "10:00",
    location: { venue: "Queenstown Town Centre", city: "Queenstown", state: "TAS", lat: -42.0824, lng: 145.5503 },
    category: "arts", tags: ["remote", "industrial", "experimental", "community"], price: 30, featured: false,
    website: "https://www.unconformity.com.au",
  },

  // ─── ACT ───────────────────────────────────────────────────────────────────
  {
    id: "evt-061",
    title: "Canberra Balloon Spectacular",
    description: "Hot air balloons fill the skies above Lake Burley Griffin at sunrise for nine magical mornings.",
    date: "2025-03-08", endDate: "2025-03-16", time: "06:30",
    location: { venue: "Glebe Park", city: "Canberra", state: "ACT", lat: -35.2809, lng: 149.1300 },
    category: "cultural", tags: ["balloons", "sunrise", "family", "free"], price: null, featured: true,
    website: "https://www.canberraballoon.com.au",
  },
  {
    id: "evt-062",
    title: "Enlighten Festival Canberra",
    description: "Canberra's national institutions illuminated with spectacular projections for three nights.",
    date: "2025-03-07", endDate: "2025-03-09", time: "20:00",
    location: { venue: "Parliamentary Triangle", city: "Canberra", state: "ACT", lat: -35.3081, lng: 149.1244 },
    category: "arts", tags: ["projections", "monuments", "free", "night"], price: null, featured: false,
    website: "https://www.enlightencanberra.com",
  },
  {
    id: "evt-063",
    title: "Floriade",
    description: "Australia's biggest celebration of spring — over a million blooms in Commonwealth Park.",
    date: "2025-09-13", endDate: "2025-10-12", time: "09:00",
    location: { venue: "Commonwealth Park", city: "Canberra", state: "ACT", lat: -35.2897, lng: 149.1365 },
    category: "cultural", tags: ["flowers", "spring", "garden", "family"], price: null, featured: true,
    website: "https://www.floriadeaustralia.com",
  },
  {
    id: "evt-064",
    title: "Canberra Comedy Festival",
    description: "A packed program of stand-up, sketch, and improv comedy from local and touring comedians.",
    date: "2025-04-09", endDate: "2025-04-13", time: "19:00",
    location: { venue: "The Street Theatre", city: "Canberra", state: "ACT", lat: -35.2806, lng: 149.1287 },
    category: "comedy", tags: ["comedy", "stand-up", "ACT"], price: 28, featured: false,
    website: "https://www.canberracomedyfestival.com.au",
  },
  {
    id: "evt-065",
    title: "National Folk Festival",
    description: "Australia's longest running folk festival — five days of music, dance, and storytelling in Canberra.",
    date: "2025-04-17", endDate: "2025-04-21", time: "10:00",
    location: { venue: "Exhibition Park", city: "Canberra", state: "ACT", lat: -35.2401, lng: 149.1018 },
    category: "music", tags: ["folk", "traditional", "dance", "storytelling"], price: 150, featured: false,
    website: "https://www.folkfestival.org.au",
  },

  // ─── NT ────────────────────────────────────────────────────────────────────
  {
    id: "evt-066",
    title: "Darwin Festival",
    description: "Celebrating the unique culture and spirit of the Northern Territory with world-class performances.",
    date: "2025-08-07", endDate: "2025-08-24", time: "17:00",
    location: { venue: "Darwin Waterfront", city: "Darwin", state: "NT", lat: -12.4634, lng: 130.8456 },
    category: "cultural", tags: ["tropical", "outdoor", "multicultural"], price: 25, featured: true,
    website: "https://www.darwinfestival.org.au",
  },
  {
    id: "evt-067",
    title: "Alice Springs Beanie Festival",
    description: "Celebrating the art of knitting — handcrafted beanies from Indigenous and non-Indigenous artists.",
    date: "2025-06-27", endDate: "2025-06-29", time: "09:00",
    location: { venue: "Araluen Arts Centre", city: "Alice Springs", state: "NT", lat: -23.7003, lng: 133.8836 },
    category: "arts", tags: ["craft", "knitting", "Indigenous", "quirky"], price: 10, featured: false,
    website: "https://www.beaniefest.org",
  },
  {
    id: "evt-068",
    title: "Barunga Festival",
    description: "A three-day cultural and sporting festival on Aboriginal land — music, ceremony, and sport.",
    date: "2025-06-06", endDate: "2025-06-08", time: "09:00",
    location: { venue: "Barunga Community", city: "Barunga", state: "NT", lat: -14.5833, lng: 132.8500 },
    category: "cultural", tags: ["Indigenous", "ceremony", "bush", "authentic"], price: 20, featured: false,
    website: "https://www.barungafestival.com.au",
  },
  {
    id: "evt-069",
    title: "Darwin Beer Can Regatta",
    description: "The world's most unusual boat race — craft made entirely from beer cans race in Darwin Harbour.",
    date: "2025-08-02", time: "10:00",
    location: { venue: "Mindil Beach", city: "Darwin", state: "NT", lat: -12.4517, lng: 130.8378 },
    category: "cultural", tags: ["beer cans", "quirky", "harbour", "family"], price: null, featured: false,
    website: "https://www.beercanregatta.org.au",
  },
  {
    id: "evt-070",
    title: "Mindil Beach Sunset Market",
    description: "Darwin's beloved outdoor market at sunset — food stalls, crafts, and live music by the sea.",
    date: "2025-04-10", time: "16:00",
    location: { venue: "Mindil Beach Reserve", city: "Darwin", state: "NT", lat: -12.4517, lng: 130.8378 },
    category: "markets", tags: ["sunset", "food", "crafts", "tropical"], price: null, featured: false,
    website: "https://www.mindil.com.au",
  },
  {
    id: "evt-071",
    title: "Alice Springs Camel Cup",
    description: "The outback's most unique sporting event — camel racing in the red centre of Australia.",
    date: "2025-07-12", time: "09:00",
    location: { venue: "Blatherskite Park", city: "Alice Springs", state: "NT", lat: -23.7059, lng: 133.8726 },
    category: "sports", tags: ["camel", "outback", "quirky", "family"], price: 20, featured: false,
    website: "https://www.camelcup.com.au",
  },
  {
    id: "evt-072",
    title: "Darwin International Film Festival",
    description: "Celebrating Australian and international cinema in the tropical Top End.",
    date: "2025-08-22", endDate: "2025-08-31", time: "11:00",
    location: { venue: "Darwin Convention Centre", city: "Darwin", state: "NT", lat: -12.4629, lng: 130.8418 },
    category: "film", tags: ["international", "tropical", "cinema", "documentary"], price: 18, featured: false,
    website: "https://www.darwinfilmfestival.com.au",
  },

  // ─── Additional Regionals ───────────────────────────────────────────────────
  {
    id: "evt-073",
    title: "Harvest Rock Festival",
    description: "Adelaide's boutique rock festival at Botanic Park with a stellar international lineup.",
    date: "2025-11-22", time: "13:00",
    location: { venue: "Botanic Park", city: "Adelaide", state: "SA", lat: -34.9156, lng: 138.6120 },
    category: "music", tags: ["rock", "alternative", "boutique", "outdoor"], price: 175, featured: false,
    website: "https://www.harvestrock.com.au",
  },
  {
    id: "evt-074",
    title: "Port Fairy Folk Festival",
    description: "One of the world's great folk festivals — four days of music in the charming coastal town of Port Fairy.",
    date: "2025-03-07", endDate: "2025-03-10", time: "11:00",
    location: { venue: "Various Venues", city: "Port Fairy", state: "VIC", lat: -38.3821, lng: 142.2361 },
    category: "music", tags: ["folk", "coastal", "family", "boutique"], price: 200, featured: false,
    website: "https://www.portfairyfolkfestival.com",
  },
  {
    id: "evt-075",
    title: "Cairns Amateurs Raceday",
    description: "The social event of the year in Far North Queensland — fashion, racing, and tropical fun.",
    date: "2025-07-25", endDate: "2025-07-26", time: "11:00",
    location: { venue: "Cannon Park Racecourse", city: "Cairns", state: "QLD", lat: -16.9390, lng: 145.7423 },
    category: "sports", tags: ["horse racing", "fashion", "tropical", "social"], price: 45, featured: false,
    website: "https://www.cairnsracing.com.au",
  },
  {
    id: "evt-076",
    title: "Fremantle Festival",
    description: "Fremantle's vibrant street arts festival celebrating creativity, culture, and community spirit.",
    date: "2025-10-25", endDate: "2025-11-02", time: "10:00",
    location: { venue: "Fremantle CBD", city: "Fremantle", state: "WA", lat: -32.0569, lng: 115.7594 },
    category: "arts", tags: ["street arts", "community", "free", "outdoor"], price: null, featured: false,
    website: "https://www.fremantlefestival.com.au",
  },
  {
    id: "evt-077",
    title: "Ballarat Begonia Festival",
    description: "Celebrating the spectacular begonia display in Ballarat's Botanical Gardens since 1953.",
    date: "2025-03-01", endDate: "2025-03-03", time: "09:00",
    location: { venue: "Ballarat Botanical Gardens", city: "Ballarat", state: "VIC", lat: -37.5560, lng: 143.8582 },
    category: "cultural", tags: ["flowers", "heritage", "family", "garden"], price: null, featured: false,
    website: "https://www.begoniafestival.com",
  },
  {
    id: "evt-078",
    title: "Bendigo Blues & Roots Festival",
    description: "A weekend of world-class blues, roots, soul, and country in the heart of regional Victoria.",
    date: "2025-05-09", endDate: "2025-05-11", time: "12:00",
    location: { venue: "The Foundry", city: "Bendigo", state: "VIC", lat: -36.7570, lng: 144.2794 },
    category: "music", tags: ["blues", "roots", "soul", "regional"], price: 95, featured: false,
    website: "https://www.bendigoblues.com.au",
  },
  {
    id: "evt-079",
    title: "Sunshine Coast Marathon",
    description: "A scenic run along the beautiful Sunshine Coast beaches, from Noosa to Mooloolaba.",
    date: "2025-08-02", time: "06:00",
    location: { venue: "Noosa Main Beach", city: "Noosa", state: "QLD", lat: -26.3928, lng: 153.0905 },
    category: "sports", tags: ["running", "marathon", "beach", "Queensland"], price: 75, featured: false,
    website: "https://www.sunshinecoastmarathon.com.au",
  },
  {
    id: "evt-080",
    title: "Big Day Out Adelaide",
    description: "One of the biggest annual music events in South Australia with massive local and international acts.",
    date: "2025-02-01", time: "12:00",
    location: { venue: "Adelaide Showground", city: "Adelaide", state: "SA", lat: -34.9411, lng: 138.5895 },
    category: "music", tags: ["rock", "pop", "electronic", "massive"], price: 189, featured: false,
    website: "https://www.bigdayout.com",
  },
];

export const CATEGORY_META: Record<
  string,
  { label: string; color: string; bg: string }
> = {
  music:    { label: "Music",    color: "#FF6B6B", bg: "#FFF0EF" },
  food:     { label: "Food",     color: "#FF9F43", bg: "#FFF4E6" },
  sports:   { label: "Sports",   color: "#4ECDC4", bg: "#E8FAF9" },
  arts:     { label: "Arts",     color: "#A29BFE", bg: "#F3F1FF" },
  cultural: { label: "Cultural", color: "#FDCB6E", bg: "#FFFBE6" },
  markets:  { label: "Markets",  color: "#55EFC4", bg: "#E8FBF5" },
  comedy:   { label: "Comedy",   color: "#FD79A8", bg: "#FFF0F5" },
  film:     { label: "Film",     color: "#636E72", bg: "#F0F1F2" },
  all:      { label: "All",      color: "#8898AA", bg: "#F4F6F8" },
};

export function getEventsByMonth(year: number, month: number): Event[] {
  return MOCK_EVENTS.filter((e) => {
    const d = new Date(e.date);
    return d.getFullYear() === year && d.getMonth() === month;
  });
}

export function getEventsByCategory(category: string): Event[] {
  if (category === "all") return MOCK_EVENTS;
  return MOCK_EVENTS.filter((e) => e.category === category);
}

export function getEventsByState(state: string): Event[] {
  if (state === "all") return MOCK_EVENTS;
  return MOCK_EVENTS.filter((e) => e.location.state === state);
}

export function getFeaturedEvents(): Event[] {
  return MOCK_EVENTS.filter((e) => e.featured);
}
